### ISSUE TITLE
Fails for logs which are shorter than OUTPUT_LIMIT

### ISSUE THREAD

**Issue by fractos** [ozantunca/elb-log-analyzer#1]
Hi, this is probably a bit niche, but I encountered it while working with an 8 line log file during testing. The output loops at the end will fail if there are less than OUTPUT_LIMIT lines in a log, as the 'log' variable it pops or shifts from 'logs' will eventually be undefined. However, if I add a test for whether 'log' is undefined, then I can get around that. There's probably a better way if it knows how many lines the log actually has, but I haven't looked into it.

**Comment by ozantunca** [comment]
Thanks for your interest. I checked the error you mentioned but it seems to be working. 

OUTPUT_LIMIT checks whether number of lines are less than default OUTPUT_LIMIT. But it fails if requested OUTPUT_LIMIT is more than the number of lines. I'll be fixing that soon. Thanks!

![screen shot 2015-05-27 at 14 42 48](https://cloud.githubusercontent.com/assets/1837579/7835193/863ddf42-047f-11e5-94fb-c4921e8f4c33.png)
