### ISSUE TITLE
isTTY is undefined

### ISSUE THREAD

**Issue by jazzl0ver** [ozantunca/elb-log-analyzer#10]
Under nodejs 0.10.x the following error occurs:
$ elb-log-analyzer logs/ --col2=client --limit=10
An error occured:  TypeError: Cannot read property 'isTTY' of undefined

The fix is to change the call to createInterface() (lib.js line 135) from
```
      var RL = _readline2.default.createInterface({
        input: _fs2.default.createReadStream(file)
      });
````
to
```
      var RL = _readline2.default.createInterface({
        terminal: false,
        input: _fs2.default.createReadStream(file)
      });
````
Please, apply.

**Comment by ozantunca** [comment]
I didn't put much effort to support 0.10.x to be honest. I'm glad that it turned to be easy. Thanks for reporting and it should be fixed now.
