### ISSUE TITLE
Install on ubuntu 14.04

### ISSUE THREAD

**Issue by fabioce** [ozantunca/elb-log-analyzer#11]
Hi,
I'm trying to use this tool with ubuntu 14.04.
I installed only npm node nodejs with apt-get install
After I send with root privileges this command:
npm install -g elb-log-analyzer
and all packets installed, but if I send to my shell:
elb-log-analyzer -v
nothing appaers.
The same if I try to analyze a directory:
elb-log-analyzer /home/ubuntu/logs/
nothing nothing.
Why?
Thanks

**Comment by ozantunca** [comment]
Hi Fabio,

Thanks for reporting this. The problem is related to the fact that Node.js in apt-get repository is 
quite outdated. Try installing it via below code:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```
This is also the suggested way of installing Node.js in [official Node.js website](https://nodejs.org/en/download/package-manager/).
