### ISSUE TITLE
Does not fit the Application ELB 

### ISSUE THREAD

**Issue by innovia** [ozantunca/elb-log-analyzer#12]
this would not work with the new elb log format

type timestamp elb client:port target:port request_processing_time target_processing_time response_processing_time elb_status_code target_status_code received_bytes sent_bytes "request" "user_agent" ssl_cipher ssl_protocol target_group_arn trace_id

**Comment by ozantunca** [comment]
Thanks for reporting. I'll look into that as soon as possible.

**Comment by ozantunca** [comment]
It should be working now. It would be great if you can update and check it again.

**Comment by innovia** [comment]
I don't understand how to install

I tried `sudo npm install -g elb-log-analyzer`

i see the following:

```
/usr/local/bin/elb-log-analyzer -> /usr/local/lib/node_modules/elb-log-analyzer/dist/cli.js
elb-log-analyzer@1.0.4 /usr/local/lib/node_modules/elb-log-analyzer
├── underscore@1.8.3
├── progress@1.1.8
├── colors@1.1.2
├── bluebird@3.4.6
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── glob@7.1.1 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.3)
├── async@2.1.4 (lodash@4.17.2)
└── babel-polyfill@6.16.0 (regenerator-runtime@0.9.6, babel-runtime@6.18.0, core-js@2.4.1)
```

`elb-log-anlyzer --version ` shows v1.0.0

also tried cloning and running npm install
then attempt to run cli.js fails

```
node dist/cli.js --version
v1.0.0
```

**Comment by ozantunca** [comment]
Apparently version number returned by the command was wrong. A foolish mistake of mine. Fixed it now. Your way of updating is correct.

**Comment by innovia** [comment]
so here are the bugs:
1) you need to add an if line match so that it doesn't through the error on line 324 and ATTRIBUTES is not nil (in case the file is corrupted or simply not a log file)

```
var ATTRIBUTES = line.match(/[^\s"']+|"([^"]*)"/gi);

if ATTRIBUTES
parse

else

continue

```
elb-log-analyzer ../elb-logs                                                          
/usr/local/lib/node_modules/elb-log-analyzer/dist/lib.js:324
    'timestamp': ATTRIBUTES[0],
                           ^

TypeError: Cannot read property '0' of null
    at parseLine (/usr/local/lib/node_modules/elb-log-analyzer/dist/lib.js:324:28)
```

2) you missed the "type" so now you need to shift all the attributes 1 up
usually its http or https

3) it doesn't display a thing when it's done processing
```
elb-log-analyzer ../elb-logs                                                     
 processing [==============================] 100% 0.0s
```
here's a log file sample

```
https 2016-11-23T00:43:36.802774Z app/prd-elb/9bb21a626f7e7660 80.82.65.90:47372 - -1 -1 -1 503 - 131 381 "GET https://54.149.1.299:443//recordings/ HTTP/1.1" "libwww-perl/6.15" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/prd-instances/ed26c7347aa20ca1 "Root=1-5834e638-4ce6fbe536f2a4fa14041b73"
https 2016-11-23T00:43:37.267432Z app/prd-elb/9bb21a626f7e7660 80.82.65.90:47447 - -1 -1 -1 400 - 131 419 "GET http://54.149.1.299:443//recordings/ HTTP/1.1" "libwww-perl/6.15" - -  "-"
h2 2016-11-23T09:45:34.610526Z app/prd-elb/9bb21a626f7e7660 79.177.235.48:59169 10.0.30.175:8080 0.001 0.262 0.000 403 403 6983 137 "POST https://api.server.com:443/store/v1/purchase HTTP/2.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/prd-instances/ed26c7347aa20ca1 "Root=1-5835653e-44b57de95515fb6023a75e50"
h2 2016-11-23T09:46:31.832776Z app/prd-elb/9bb21a626f7e7660 79.177.235.48:59169 10.0.30.175:8080 0.000 0.334 0.000 200 200 6792 253 "POST https://api.server.com:443/store/v1/purchase HTTP/2.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/prd-instances/ed26c7347aa20ca1 "Root=1-58356577-5b50b6d35a9c7b527351abbc"
https 2016-11-23T10:23:30.067177Z app/prd-elb/9bb21a626f7e7660 46.105.97.78:56277 - -1 -1 -1 400 - 46 321 "GET http://prd-elb-12345678910.us-west-2.elb.amazonaws.com:443/w00tw00t.at.ISC.SANS.DFind:) HTTP/1.1" "-" - -  "-"
h2 2016-11-23T13:44:48.359207Z app/prd-elb/9bb21a626f7e7660 79.181.29.107:53045 10.0.10.66:8080 0.001 0.234 0.000 500 500 7025 260 "POST https://api.server.com:443/store/v1/purchase HTTP/2.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/prd-instances/ed26c7347aa20ca1 "Root=1-58359d50-61c4d29308af67626c768772"
h2 2016-11-23T13:44:58.213783Z app/prd-elb/9bb21a626f7e7660 79.181.29.107:53045 10.0.10.66:8080 0.000 0.014 0.000 500 500 6752 260 "POST https://api.server.com:443/store/v1/purchase HTTP/2.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/prd-instances/ed26c7347aa20ca1 "Root=1-58359d5a-521de85f27544c721d262df8"
h2 2016-11-23T13:46:11.392026Z app/prd-elb/9bb21a626f7e7660 79.181.29.107:53045 10.0.10.66:8080 0.001 0.252 0.000 200 200 6521 237 "POST https://api.server.com:443/store/v1/purchase HTTP/2.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/prd-instances/ed26c7347aa20ca1 "Root=1-58359da3-458ae1af1dec77b62679e61a"
https 2016-11-23T13:55:35.092470Z app/prd-elb/9bb21a626f7e7660 183.129.160.229:43961 - -1 -1 -1 400 - 0 321 "- http://prd-elb-12345678910.us-west-2.elb.amazonaws.com:443- -" "-" - -  "-"
h2 2016-11-23T14:16:11.926994Z app/prd-elb/9bb21a626f7e7660 79.176.4.60:57527 10.0.30.73:8080 0.001 0.444 0.000 200 200 6791 237 "POST https://api.server.com:443/store/v1/purchase HTTP/2.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/prd-instances/ed26c7347aa20ca1 "Root=1-5835a4ab-40d7079b419f6eae35e18786"

```

**Comment by ozantunca** [comment]
Hi. Where did you get these logs? I don't see `protocol` field in [documentation](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html#access-log-entry-format).

**Comment by ozantunca** [comment]
Ok I found it. There are two kinds of Elastic Load Balancers: classic and application. Apparently they have different log structures. [Classic ELB logs](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html#access-log-entry-format), [Application ELB logs](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-format). Application ELB logs start with a `type` field as you mentioned that classic ELB doesn't have. This issue has to be resolved in a way that the module should work in both versions.

**Comment by ozantunca** [comment]
It should be working with both classic and application ELB logs now.

**Comment by innovia** [comment]
Awesome! thanks for the update it works
