### ISSUE TITLE
does not aggregate properly

### ISSUE THREAD

**Issue by zhaoboli** [ozantunca/elb-log-analyzer#13]
it seems that it's trimming off some of the log entires when aggregating.
When i tried to run the below command for a single file
elb-log-analyzer <some_log_file.log> --col1=count --col2=elb_status_code --sortBy=2, I am able to get the below result, with elb_status_code 504 entry captured in the result.
1 - 1 - 504
2 - 174 - 404
3 - 36084 - 200
However, when I tried to generate the result on all the log files on the same directory, the elb_status_code 504 entry is not showing up on the result, only 404 and 200 is there.
elb-log-analyzer *.log --col1=count --col2=elb_status_code --sortBy=2
1 - 6168 - 404
2 - 965280 - 200

**Comment by ozantunca** [comment]
Thanks for reporting. After inspecting the issue, I realized that it's related to an issue when using "*.log" or similar patterns when selecting files. Would be great if you can update the module to version 1.0.4 and try again.

**Comment by zhaoboli** [comment]
Just tested it and it's working now. Thank you for the quick fix!
