### ISSUE TITLE
Question : Does elb-log-analyzer support backend_status_code?

### ISSUE THREAD

**Issue by soramesso** [ozantunca/elb-log-analyzer#14]
I’d be glad if elb-log-analyzer would support "backend_status_code".

I ran the following command:

```bash
elb-log-analyzer ./  --col1=count --col2=elb_status_code --col3=backend_status_code
```

```bash
1 - 4 - 503 - 150
2 - 2 - 404 - 404
3 - 2 - 503 - 208
4 - 2 - 503 - 163
5 - 2 - 503 - 566
6 - 2 - 503 - 565
```

The fourth column seems to display "received_bytes".
Because there is no HTTP status code 566.

If backend_status_code is supported, could you tell me how to specify it?

**Comment by ozantunca** [comment]
Thanks for reporting the issue. Are the logs from a Classic Load Balancer or an Application Load Balancer?

**Comment by soramesso** [comment]
Thanks for your reply.
It is a log of the Classic Load Balancer.

Sample:
```text
xxxxxxxxxxxx_elasticloadbalancing_ap-northeast-1_xxx_20170626T0900Z_172.27.26.156_xxxxxxx.txt:2017-06-26T08:38:27.991796Z xxxxxxx 172.27.19.150:43326 172.27.19.217:80 0.00008 0.000626 0.000057 503 503 566 326 "POST http://internal-xxx.ap-northeast-1.elb.amazonaws.com:80/api/v1/hoge HTTP/1.0" "Xxxx/1.0.4 (iPad; iOS 10.3.2; Scale/2.00)" - -
```

And, Does elb-log-analyzer support  Application Load Balancer?

**Comment by ozantunca** [comment]
Sorry for this late reply. On the example you provided, I see that the line starts with the `log file name` + `timestamp` whereas it should start with just `timestamp`. This is how ELB access logs are defined in the documentation. That seems to mess with parsing. Application Load Balancer logs have a little bit different structure so it's not reliably supported. Full support for that will be added soon.
