### ISSUE TITLE
Breakdown of request field (HTTP method, Host header, etc)

### ISSUE THREAD

**Issue by gerrytan** [ozantunca/elb-log-analyzer#19]
Need capability to count by sub-attribute of request fields (eg: HTTP method, host header, etc).

Sample requirement: count requests by host header

Sample session / output:
```
$ npx elb-log-analyzer foobar-logs/ --col2=host_header
1 - 224 - en.foobar.com
2 - 187 - zh.foobar.com
```

**Comment by ozantunca** [comment]
Hi there. Thanks for reporting. This was requested before as well. I guess I should get to it.

**Comment by ozantunca** [comment]
These changes are included in v1.3

**Comment by gerrytan** [comment]
Thanks a lot @ozatunca, would be nice if this is mentioned in CHANGELOG.md

**Comment by ozantunca** [comment]
Thanks for reminding. I've added them.
