### ISSUE TITLE
Stream logs

### ISSUE THREAD

**Issue by maxrabin** [ozantunca/elb-log-analyzer#3]
Instead of loading the whole file into memory with `fs.readFile` use `fs.createReadStream` as an input to `readline`.

**Comment by ozantunca** [comment]
I agree that using `fs.createReadStream` instead of `fs.readFile` would perform better but do we need [readline](https://nodejs.org/api/readline.html) here?

**Comment by maxrabin** [comment]
Its a streaming library that splits by newline. If you don't use it while streaming you'll get a chunk with half a line then another chunk with the other half of the line. You can deal with that yourself but its super easy to just use `readline`

**Comment by ozantunca** [comment]
Ok, I see now. Thanks for clarifying that. I'll be implementing this improvement shortly.

**Comment by tirolo** [comment]
Am I right to assume this is probably the reason why I'm getting `process out of memory` exception when trying to load 1.5Gb worth of logs?

**Comment by maxrabin** [comment]
Most likely. Node.js has a limit of 1GB of memory per process, and if you're loading a file that takes up memory, then split into array of strings that takes up the memory again, etc.

**Comment by tirolo** [comment]
I've done the `--max-old-space-size=8192` thing but I'm still not able to parse a day of logs, do you have any suggestions on how I could get it?

**Comment by maxrabin** [comment]
Split the file into smaller files using `split` (a standard command line utility) for now.

**Comment by tirolo** [comment]
they are already 1 to 6mb files... tried to figure out if there's somewhere in the code that is not releasing the resource but I'm not familiar with node... does fs.Read release its resources on, for instance, https://github.com/ozantunca/elb-log-analyzer/blob/master/index.js#L69 ? Can you guys spot anything that might be holding on resources that it shouldn't? Maybe some sort of `using` (as in C#) block that could give is a quick win?

**Comment by ozantunca** [comment]
I'm sorry for this late reply. I have been refactoring and experimenting on the module. Unfortunately replacing `fs.readFile` with `fs.createReadStream` alone does not make much difference performance-wise. To make a real impact on memory usage of the module, it has to be rewritten to work by analyzing logs line by line as soon as they are read via `fs.createReadStream`. This requires quite a bit refactoring. I expect to complete it in the next couple of days. I'm leaving this issue open until then and will comment here when the new version is available. Thanks for your interest in this module guys.

**Comment by maxrabin** [comment]
Thanks! Today I tried using the script again today and ran into the memory issue. The general structure should be something like:

    var sum = 0;
    var fstream = fs. createReadStream('./myFile');
    var rl = readline.createInterface({
        terminal: false,
        input: s,
    });
    rl.on('line', function (line) {
        sum += line.length;
    });
    rl.on('end', function () {
        console.log("total line length: " + sum);
    });

**Comment by ozantunca** [comment]
I rolled out a new version that processes logs line be line using a stream of input. I tested new version on millions of lines of code but it didn't go out of memory. It should be much more performant now. I would appreciate if you can test it out and provide some feedback if you run into an issue.

**Comment by tirolo** [comment]
Tested against version 0.3.1 (from npm feed), 922 log files, total size 3GB.

Sometimes I get blank result (it just finishes without showing anything) and sometimes I still get the memory exception.

```
D:\Logs\elb-prod\2016-02>elb-log-analyzer 01/

<--- Last few GCs --->

  138635 ms: Scavenge 1414.1 (1448.5) -> 1414.1 (1448.5) MB, 18.2 / 0 ms (+ 0.0
ms in 1 steps since last GC) [allocation failure] [incremental marking delaying
mark-sweep].
  139854 ms: Mark-sweep 1414.1 (1448.5) -> 1414.1 (1448.5) MB, 1219.8 / 0 ms (+
0.0 ms in 1 steps since start of marking, biggest step 0.0 ms) [last resort gc].

  141077 ms: Mark-sweep 1414.1 (1448.5) -> 1414.1 (1448.5) MB, 1223.3 / 0 ms [la
st resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000036090E44A59 <JS Object>
    1: parse [native json.js:~43] [pc=0000027032FE8B1D] (this=0000036090E457E1 <
a JSON with map 0000019F4BC13251>,s=00000019F1F66931 <String[71]: ["http://www.website.com:80/someletters/moreletters.asp?asd=15&param=117&text=184274"]>,m=0000036090E04139 <u
ndefined>)
    2: arguments adaptor frame: 1->2
    3: /* anonymous */(aka /* anonymous */) [C:\Users\me\AppData\Roa
ming\npm\node_modules\elb-l...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

D:\Logs\elb-prod\2016-02>
```

But it works if I run with `--max-old-space-size=8192` (I can now process at least one day of logs). 

Great job, thanks again!

**Comment by ozantunca** [comment]
If you are using `elb-log-analyzer` to count rows, it might go out of memory since there will be as much items in the memory as the number of unique lines of logs with requested columns. If you are not counting lines and just sorting them, you shouldn't go out of memory because new version is programmed to only store a few items in the memory. For instance if you requested 25 lines, `elb-log-analyzer` will only store 25 lines in the memory and will discard the rest. 

I will investigate the "blank result" thing though. Thanks for your feedback!
