### ISSUE TITLE
--prefix is not working

### ISSUE THREAD

**Issue by joshma** [ozantunca/elb-log-analyzer#6]
It looks like the `--prefixN` option isn't doing anything, just wanted to send in a bug report:
```
elb-log-analyzer /tmp/elb-logs/*.log --col1=count --col2=requested_resource --prefix2=https://notbenchling.com/
1 - 163168 - https://benchling.com:443/1/api/_poll
...etc...
```

**Comment by ozantunca** [comment]
Sorry for addressing this issue quite late. I was very busy recently. It should be fixed now.
