### ISSUE TITLE
add an option to group by client ip addresses rather than by client ip and port pair

### ISSUE THREAD

**Issue by jazzl0ver** [ozantunca/elb-log-analyzer#7]
the easy fix is to add the following two lines in the end of parseLine function (lib.js) before return statement:
  var t = ATTRIBUTES[2].split(':');
  ATTRIBUTES[2] = t[0];

**Comment by ozantunca** [comment]
I see. But grouping by clientip:port pair can also be useful and desired by some users. We cannot just remove that. There should be a better way.

**Comment by jazzl0ver** [comment]
Yeah, I didn't mean to replace it. Adding extra option would be great.

**Comment by jazzl0ver** [comment]
Thank you!!
