### ISSUE TITLE
Feature request: add timestamp filters (start / end)

### ISSUE THREAD

**Issue by guillaumemolter** [ozantunca/elb-log-analyzer#8]
Would be great to be able to filter the logs for specific timestamp.

Something like:
`--start 2016-05-18T22:33:06.409345Z  --end 2016-05-18T22:38:58.279273Z`

**Comment by ozantunca** [comment]
Sounds reasonable. I will look into it.

**Comment by guillaumemolter** [comment]
Thanks!
